
# redis-cli -a operator@redis@2019 --cluster create 172.16.238.11:6379 172.16.238.12:6379 172.16.238.13:6379 172.16.238.14:6379 172.16.238.15:6379 172.16.238.16:6379 --cluster-replicas 1
version: '3.3'
services:
  # 节点1
  redis1:
    # 启动之后的容器名称
    container_name: redis-node-1
    env_file: 
      # 环境配置
      - ./.env
    # 使用哪种镜像
    image: redis
    # 端口映射
    ports:
      - ${redis1_ports}
      - ${redis1_cluster}
    networks:
      - operator
    volumes:
      # 容器的data映射到宿主机
      - /data/redis/node-${redis1_port}/data:/data
      # 加载配置文件
      - /data/redis/node-${redis1_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment: 
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点2
  redis2:
    container_name: redis-node-2
    env_file: 
      - ./.env
    # 使用哪种镜像
    image: redis
    # 端口映射
    ports:
      - ${redis2_ports}
      - ${redis2_cluster}
    networks:
      - operator
    volumes:
      # 容器的data映射到宿主机
      - /data/redis/node-${redis2_port}/data:/data
      # 加载配置文件
      - /data/redis/node-${redis2_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件  
    command: redis-server /usr/local/etc/redis/redis.conf
    environment: 
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点3
  redis3:
    container_name: redis-node-3
    env_file:
      - ./.env
    # 使用哪种镜像
    image: redis
    # 端口映射
    ports:
      - ${redis3_ports}
      - ${redis3_cluster}
    networks:
      - operator
    volumes:
      # 容器的data映射到宿主机
      - /data/redis/node-${redis3_port}/data:/data
      # 加载配置文件
      - /data/redis/node-${redis3_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点4
  redis4:
    container_name: redis-node-4
    env_file:
      - ./.env
    # 使用哪种镜像
    image: redis
    # 端口映射
    ports:
      - ${redis4_ports}
      - ${redis4_cluster}
    networks:
      - operator
    volumes:
      # 容器的data映射到宿主机
      - /data/redis/node-${redis4_port}/data:/data
      # 加载配置文件
      - /data/redis/node-${redis4_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点5
  redis5:
    container_name: redis-node-5
    env_file:
      - ./.env
    # 使用哪种镜像
    image: redis
    # 端口映射
    ports:
      - ${redis5_ports}
      - ${redis5_cluster}
    networks:
      - operator
    volumes:
      # 容器的data映射到宿主机
      - /data/redis/node-${redis5_port}/data:/data
      # 加载配置文件
      - /data/redis/node-${redis5_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点6
  redis6:
    container_name: redis-node-6
    env_file:
      - ./.env
    # 使用哪种镜像
    image: redis
    # 端口映射
    ports:
      - ${redis6_ports}
      - ${redis6_cluster}
    networks:
        cluster-net:
          ipv4_address: 172.16.238.16
    volumes:
      # 容器的data映射到宿主机
      - /data/redis/node-${redis6_port}/data:/data
      # 加载配置文件
      - /data/redis/node-${redis6_port}/redis.conf:/usr/local/etc/redis/redis.conf
    # 启动redis的时候指定配置文件
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  sentinel-9001:
    container_name: sentinel-9001
    image: redis
    ports:
      - 26379:26379
    networks:
      - operator
    volumes:
      - /data/redis/sentinel-9001/data:/data
      - /data/redis/sentinel-9001/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
networks:
  operator:
#networks:
#  # 创建集群网络，在容器之间通信
#  cluster-net:
#    ipam:
#      config:
#        - subnet: 172.16.238.0/24